### ISSUE TITLE
OSM feature layers not supported

### ISSUE THREAD

**Issue by penpendede** [KlausBenndorf/guide4you#110]
I use the Hydda style that comes with a OSM base layer and an OSM feature layer. The former has the terrain, the latter the outlines of streets plus street names and other labels. This obviously is nothing odd (in a similar manner WMS servers provide feature layers as images that have transparent parts). However I get **Error: OSM is not configured for superType 'featureLayer'**

URL for base layer: https://{a-c}.tile.openstreetmap.se/hydda/base/{z}/{x}/{y}.png
URL for feature layer: https://{a-c}.tile.openstreetmap.se/hydda/roads_and_labels/{z}/{x}/{y}.png

As an alternative I tried to make roads_and_labels a base layer and simply display both base layers at the same time. In principle this works, both base layers are displayed. However, the attribution vanishes as soon as I make visible a second base layer. It is no issue with the two identical attribution strings I use. Each  correctly displays if a single base layer is visible (no matter which one) but the attribution control altogether vanishes as soon as the second is set to visible as well.

I think fixing the first issue makes more sense than allowing for multiple base layers that are displayed at the same time - as the latter messes up the very concept of a base layer.

**Comment by simonseyock** [comment]
Introduced by #119
