### ISSUE TITLE
fitExtent broken

### ISSUE THREAD

**Issue by penpendede** [KlausBenndorf/guide4you#173]
Neither does fitExtent make the view fit the given extent nor can it be used without also setting center and zoom. This means that there is no way to ensure that a certain region is displayed as center and initial zoom do not take into account different screen sizes. Note that fitExtent is known to have worked before, hence the *broken*.

**Comment by simonseyock** [comment]
The configuration option is named 'fit':
https://github.com/KlausBenndorf/guide4you/blob/master/src/configurators/MapConfigurator.js#L65
