### ISSUE TITLE
Adding WMS layer: cannot localise 'LayerSelector featureInfo show': Not in dictionary

### ISSUE THREAD

**Issue by SamOxyPlot** [KlausBenndorf/guide4you#359]
Hello

Can someone please help me out with adding an WMS layer (from GeoServer) via the Guide4You library?
Is there a sample available?

Adding the code below results in this error:
**“g4u.js?v=163:1024 Cannot localise 'LayerSelector featureInfo show': Not in dictionary”**

```
var layerConfig = {
   "id": "XXX",
   "title": "XXX",
   "code": "XXX",
   "type": "WMS",
   "source": {
      "url": "REPLACED URL…/geoserver/XXX/ows?",
      "params": { 'LAYERS': 'XX:XX' },
      "serverType": 'geoserver',
      "crossOrigin": 'anonymous'
                  },
   "visible": true
}
 
var layer = map.get('api').addBaseLayer(layerConfig);
```

**Thanks in advance!**

Kind regards

**Comment by simonseyock** [comment]
Your `l10n.json` file seems to be missing the `LayerSelector featureInfo show` key.

In the repository it looks like this: https://github.com/KlausBenndorf/guide4you/blob/master/files/l10n.json.js#L158

**Comment by simonseyock** [comment]
You can use a tool like http://jsondiff.com/ to compare the json files (you find a 'compiled' one in the dist folder here: https://github.com/KlausBenndorf/guide4you/blob/master/dist/files/l10n.json)

**Comment by SamOxyPlot** [comment]
Thanks Simon. Problem solved!
