### ISSUE TITLE
Add a dist-folder to npm-package

### ISSUE THREAD

**Issue by penpendede** [KlausBenndorf/guide4you#50]
If you use

> npm install guide4you

and change directory to **node_modules/guide4you** you'd expect that you can issue

> npm run dev conf/simple

Tried it. Tons of error messages. First expected the version of **guide4you-builder** to be incompatible but that wasn't the case. Turns out that when in said directory you first need to issue **npm install** which installs tons of packages that are already present after **npm install guide4you** - just to another directory.

According to me this oddity should at least be documented.

**Comment by ischas** [comment]
Maybe related to the imports of the licenses? e.g. `import 'file?name=licenses/OpenLayers.txt!node_modules/openlayers/LICENSE.md'` Here the node_module folder is referenced directly.

**Comment by simonseyock** [comment]
I disagree. If you install something with npm you normally want to use it as a dependency. That is the reason why no devDependecies get installed. (That is the whole purpose of devDependecies in the first place) I would definitely not expect something I installed as a dependency to build.

We could add this to the documentation nevertheless. 

What I think would be great for the npm package is a prebuilt guide4you which can directly be included into a webpage. This would be accord with nearly every other npm package I know.

**Comment by simonseyock** [comment]
And if I would install a package standalone not as a dependency I would still expect I would need to follow the build instructions in the reade ;)

**Comment by ischas** [comment]
We should add a dist-folder to the npm-package with a prebuilt client including the simple-configuration. 

We still have to discuss how to create distributions of modules. By now they are included while build in the entry.js. There are several points which have to be solved:
- We should expose the module configuration to the constructor
- The distributed modules should have no doubled code so the build process has to be changed

Any other suggestions?
